# Generated by Django 5.0.6 on 2024-06-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
        migrations.AlterField(
            model_name="notes",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="media/"),
        ),
        migrations.AlterField(
            model_name="tutorial",
            name="thumb",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
        migrations.AlterField(
            model_name="tutorial",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, default="media/lufy.png", upload_to="media/"
            ),
        ),
    ]
