# Generated by Django 5.0.6 on 2024-06-07 10:15

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0002_alter_notes_cover_alter_notes_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorial",
            name="video",
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
