# Generated by Django 5.0.6 on 2024-06-07 11:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0003_alter_tutorial_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_announcements_check",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
